export type NotificationStatus =
    | 'POSTIT_CREATED'
    | 'POSTIT_REPLY'
    | 'POSTIT_LIKED'
    | 'POSTIT_PINNED'
    | 'POSTIT_MENTION'
    | 'REPORT_CREATED'
    | 'REPORT_REVIEW'
    | 'REPORT_RESOLVED'
    | 'REPORT_REJECTED'
    | 'ACCOUNT_BADGE_UNLOCKED'
    | 'ACCOUNT_NEW_FOLLOW'
    | 'ACCOUNT_SUSPENDED'
    | 'ACCOUNT_BANNED'
    | 'ACCOUNT_ROLE_UPDATED'
    | 'WALL_INVITATION'
    | 'WALL_JOIN_REQUEST'
    | 'WALL_JOIN_ACCEPTED'
    | 'WALL_PROMOTED'
    | 'WALL_ANNOUNCEMENT'
    | 'SYSTEM_MESSAGE'

export type ReportTargetType = 'users' | 'postit' | 'walls'

export type ReportStatus = 'PENDING' | 'REVIEW' | 'REJECTED' | 'ACCEPTED'

export type ReportReason =
    | 'SPAM'
    | 'HARASSMENT'
    | 'HATE'
    | 'NUDITY'
    | 'VIOLENCE'
    | 'FAKE_INFORMATION'
    | 'COPYRIGHT'
    | 'INAPPROPRIATE_PROFILE'
    | 'SCAM'
    | 'OFF_TOPIC'
    | 'DUPLICATE'
    | 'IMPERSONATION'
    | 'SELF_HARM'
    | 'CHILD_ABUSE'
    | 'EXTREMISM_OR_TERRORISM'
    | 'DOXING'
    | 'MALWARE_OR_PHISHING'
    | 'ILLEGAL_ACTIVITY'
    | 'OTHER'
