export const NOTIFS = [
    'POSTIT_CREATED',
    'POSTIT_REPLY',
    'POSTIT_LIKED',
    'POSTIT_PINNED',
    'POSTIT_MENTION',
    'REPORT_CREATED',
    'REPORT_REVIEW',
    'REPORT_RESOLVED',
    'REPORT_REJECTED',
    'ACCOUNT_BADGE_UNLOCKED',
    'ACCOUNT_NEW_FOLLOW',
    'ACCOUNT_SUSPENDED',
    'ACCOUNT_BANNED',
    'ACCOUNT_ROLE_UPDATED',
    'WALL_INVITATION',
    'WALL_JOIN_REQUEST',
    'WALL_JOIN_ACCEPTED',
    'WALL_PROMOTED',
    'WALL_ANNOUNCEMENT',
    'SYSTEM_MESSAGE',
] as const

export type Notif = (typeof NOTIFS)[number]
